name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./Terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # - name: Configure Google Cloud CLI
    #   uses: google-github-actions/setup-gcloud@v1
    #   with:
    #     version: 'latest'
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Init
      run: terraform init #-var-file=variables.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}



    - name: Terraform Plan
      run: terraform plan #-var-file=variables.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Apply
      run: terraform apply #-auto-approve -var-file=variables.tfvars
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    # - name: Clean up
    #   run: terraform destroy -auto-approve -var-file=variables.tfvars
